package com.example.apple.lingyongqian.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table e_allbillinfo.
 */
public class AllBillInfo {

    private Long al_pid;
    private Long al_id;
    private String al_add_date;
    private String al_bill_num;
    private Integer al_bill_type;
    private String al_bill_name;

    public AllBillInfo() {
    }

    public AllBillInfo(Long al_id) {
        this.al_id = al_id;
    }

    public AllBillInfo(Long al_pid, Long al_id, String al_add_date, String al_bill_num, Integer al_bill_type, String al_bill_name) {
        this.al_pid = al_pid;
        this.al_id = al_id;
        this.al_add_date = al_add_date;
        this.al_bill_num = al_bill_num;
        this.al_bill_type = al_bill_type;
        this.al_bill_name = al_bill_name;
    }

    public Long getAl_pid() {
        return al_pid;
    }

    public void setAl_pid(Long al_pid) {
        this.al_pid = al_pid;
    }

    public Long getAl_id() {
        return al_id;
    }

    public void setAl_id(Long al_id) {
        this.al_id = al_id;
    }

    public String getAl_add_date() {
        return al_add_date;
    }

    public void setAl_add_date(String al_add_date) {
        this.al_add_date = al_add_date;
    }

    public String getAl_bill_num() {
        return al_bill_num;
    }

    public void setAl_bill_num(String al_bill_num) {
        this.al_bill_num = al_bill_num;
    }

    public Integer getAl_bill_type() {
        return al_bill_type;
    }

    public void setAl_bill_type(Integer al_bill_type) {
        this.al_bill_type = al_bill_type;
    }

    public String getAl_bill_name() {
        return al_bill_name;
    }

    public void setAl_bill_name(String al_bill_name) {
        this.al_bill_name = al_bill_name;
    }

}
