package com.example.apple.lingyongqian.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table e_bills.
 */
public class Bills {

    private Long b_id;
    private Long b_pid;
    private String b_add_date;
    private String b_name;
    private String b_type;
    private String b_num;
    private String b_all;
    private String b_describ;

    public Bills() {
    }

    public Bills(Long b_id) {
        this.b_id = b_id;
    }

    public Bills(Long b_id, Long b_pid, String b_add_date, String b_name, String b_type, String b_num, String b_all, String b_describ) {
        this.b_id = b_id;
        this.b_pid = b_pid;
        this.b_add_date = b_add_date;
        this.b_name = b_name;
        this.b_type = b_type;
        this.b_num = b_num;
        this.b_all = b_all;
        this.b_describ = b_describ;
    }

    public Long getB_id() {
        return b_id;
    }

    public void setB_id(Long b_id) {
        this.b_id = b_id;
    }

    public Long getB_pid() {
        return b_pid;
    }

    public void setB_pid(Long b_pid) {
        this.b_pid = b_pid;
    }

    public String getB_add_date() {
        return b_add_date;
    }

    public void setB_add_date(String b_add_date) {
        this.b_add_date = b_add_date;
    }

    public String getB_name() {
        return b_name;
    }

    public void setB_name(String b_name) {
        this.b_name = b_name;
    }

    public String getB_type() {
        return b_type;
    }

    public void setB_type(String b_type) {
        this.b_type = b_type;
    }

    public String getB_num() {
        return b_num;
    }

    public void setB_num(String b_num) {
        this.b_num = b_num;
    }

    public String getB_all() {
        return b_all;
    }

    public void setB_all(String b_all) {
        this.b_all = b_all;
    }

    public String getB_describ() {
        return b_describ;
    }

    public void setB_describ(String b_describ) {
        this.b_describ = b_describ;
    }

}
