package com.example.apple.lingyongqian.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table e_companycards.
 */
public class CompanyCards implements Parcelable {

    private Long c_id;
    private Long c_pid;
    private String c_add_date;
    private String c_name;
    private String c_address;
    private String c_tell;
    private String c_email;
    private String c_describ;

    public CompanyCards() {
    }

    public CompanyCards(Long c_id) {
        this.c_id = c_id;
    }

    public CompanyCards(Long c_id, Long c_pid, String c_add_date, String c_name, String c_address, String c_tell, String c_email, String c_describ) {
        this.c_id = c_id;
        this.c_pid = c_pid;
        this.c_add_date = c_add_date;
        this.c_name = c_name;
        this.c_address = c_address;
        this.c_tell = c_tell;
        this.c_email = c_email;
        this.c_describ = c_describ;
    }

    public Long getC_id() {
        return c_id;
    }

    public void setC_id(Long c_id) {
        this.c_id = c_id;
    }

    public Long getC_pid() {
        return c_pid;
    }

    public void setC_pid(Long c_pid) {
        this.c_pid = c_pid;
    }

    public String getC_add_date() {
        return c_add_date;
    }

    public void setC_add_date(String c_add_date) {
        this.c_add_date = c_add_date;
    }

    public String getC_name() {
        return c_name;
    }

    public void setC_name(String c_name) {
        this.c_name = c_name;
    }

    public String getC_address() {
        return c_address;
    }

    public void setC_address(String c_address) {
        this.c_address = c_address;
    }

    public String getC_tell() {
        return c_tell;
    }

    public void setC_tell(String c_tell) {
        this.c_tell = c_tell;
    }

    public String getC_email() {
        return c_email;
    }

    public void setC_email(String c_email) {
        this.c_email = c_email;
    }

    public String getC_describ() {
        return c_describ;
    }

    public void setC_describ(String c_describ) {
        this.c_describ = c_describ;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.c_id);
        dest.writeValue(this.c_pid);
        dest.writeString(this.c_add_date);
        dest.writeString(this.c_name);
        dest.writeString(this.c_address);
        dest.writeString(this.c_tell);
        dest.writeString(this.c_email);
        dest.writeString(this.c_describ);
    }

    protected CompanyCards(Parcel in) {
        this.c_id = (Long) in.readValue(Long.class.getClassLoader());
        this.c_pid = (Long) in.readValue(Long.class.getClassLoader());
        this.c_add_date = in.readString();
        this.c_name = in.readString();
        this.c_address = in.readString();
        this.c_tell = in.readString();
        this.c_email = in.readString();
        this.c_describ = in.readString();
    }

    public static final Parcelable.Creator<CompanyCards> CREATOR = new Parcelable.Creator<CompanyCards>() {
        @Override
        public CompanyCards createFromParcel(Parcel source) {
            return new CompanyCards(source);
        }

        @Override
        public CompanyCards[] newArray(int size) {
            return new CompanyCards[size];
        }
    };
}
