package com.example.apple.lingyongqian.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table e_diarys.
 */
public class Diarys implements Parcelable {

    private Long d_id;
    private Long d_pid;
    private String d_add_date;
    private String d_textcontent;
    private String d_img_url;
    private String d_voice_url;
    private Integer d_feeling;

    public Diarys() {
    }

    public Diarys(Long d_id) {
        this.d_id = d_id;
    }

    public Diarys(Long d_id, Long d_pid, String d_add_date, String d_textcontent, String d_img_url, String d_voice_url, Integer d_feeling) {
        this.d_id = d_id;
        this.d_pid = d_pid;
        this.d_add_date = d_add_date;
        this.d_textcontent = d_textcontent;
        this.d_img_url = d_img_url;
        this.d_voice_url = d_voice_url;
        this.d_feeling = d_feeling;
    }

    public Long getD_id() {
        return d_id;
    }

    public void setD_id(Long d_id) {
        this.d_id = d_id;
    }

    public Long getD_pid() {
        return d_pid;
    }

    public void setD_pid(Long d_pid) {
        this.d_pid = d_pid;
    }

    public String getD_add_date() {
        return d_add_date;
    }

    public void setD_add_date(String d_add_date) {
        this.d_add_date = d_add_date;
    }

    public String getD_textcontent() {
        return d_textcontent;
    }

    public void setD_textcontent(String d_textcontent) {
        this.d_textcontent = d_textcontent;
    }

    public String getD_img_url() {
        return d_img_url;
    }

    public void setD_img_url(String d_img_url) {
        this.d_img_url = d_img_url;
    }

    public String getD_voice_url() {
        return d_voice_url;
    }

    public void setD_voice_url(String d_voice_url) {
        this.d_voice_url = d_voice_url;
    }

    public Integer getD_feeling() {
        return d_feeling;
    }

    public void setD_feeling(Integer d_feeling) {
        this.d_feeling = d_feeling;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.d_id);
        dest.writeValue(this.d_pid);
        dest.writeString(this.d_add_date);
        dest.writeString(this.d_textcontent);
        dest.writeString(this.d_img_url);
        dest.writeString(this.d_voice_url);
        dest.writeValue(this.d_feeling);
    }

    protected Diarys(Parcel in) {
        this.d_id = (Long) in.readValue(Long.class.getClassLoader());
        this.d_pid = (Long) in.readValue(Long.class.getClassLoader());
        this.d_add_date = in.readString();
        this.d_textcontent = in.readString();
        this.d_img_url = in.readString();
        this.d_voice_url = in.readString();
        this.d_feeling = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<Diarys> CREATOR = new Parcelable.Creator<Diarys>() {
        @Override
        public Diarys createFromParcel(Parcel source) {
            return new Diarys(source);
        }

        @Override
        public Diarys[] newArray(int size) {
            return new Diarys[size];
        }
    };
}
