package com.example.apple.lingyongqian.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table e_notes.
 */
public class Notes implements Parcelable {

    private Long n_id;
    private Long n_pid;
    private String n_add_date;
    private String n_textcontent;
    private String n_img_url;
    private String n_voice_url;
    private String n_isdone;

    public Notes() {
    }

    public Notes(Long n_id) {
        this.n_id = n_id;
    }

    public Notes(Long n_id, Long n_pid, String n_add_date, String n_textcontent, String n_img_url, String n_voice_url, String n_isdone) {
        this.n_id = n_id;
        this.n_pid = n_pid;
        this.n_add_date = n_add_date;
        this.n_textcontent = n_textcontent;
        this.n_img_url = n_img_url;
        this.n_voice_url = n_voice_url;
        this.n_isdone = n_isdone;
    }

    public Long getN_id() {
        return n_id;
    }

    public void setN_id(Long n_id) {
        this.n_id = n_id;
    }

    public Long getN_pid() {
        return n_pid;
    }

    public void setN_pid(Long n_pid) {
        this.n_pid = n_pid;
    }

    public String getN_add_date() {
        return n_add_date;
    }

    public void setN_add_date(String n_add_date) {
        this.n_add_date = n_add_date;
    }

    public String getN_textcontent() {
        return n_textcontent;
    }

    public void setN_textcontent(String n_textcontent) {
        this.n_textcontent = n_textcontent;
    }

    public String getN_img_url() {
        return n_img_url;
    }

    public void setN_img_url(String n_img_url) {
        this.n_img_url = n_img_url;
    }

    public String getN_voice_url() {
        return n_voice_url;
    }

    public void setN_voice_url(String n_voice_url) {
        this.n_voice_url = n_voice_url;
    }

    public String getN_isdone() {
        return n_isdone;
    }

    public void setN_isdone(String n_isdone) {
        this.n_isdone = n_isdone;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.n_id);
        dest.writeValue(this.n_pid);
        dest.writeString(this.n_add_date);
        dest.writeString(this.n_textcontent);
        dest.writeString(this.n_img_url);
        dest.writeString(this.n_voice_url);
        dest.writeString(this.n_isdone);
    }

    protected Notes(Parcel in) {
        this.n_id = (Long) in.readValue(Long.class.getClassLoader());
        this.n_pid = (Long) in.readValue(Long.class.getClassLoader());
        this.n_add_date = in.readString();
        this.n_textcontent = in.readString();
        this.n_img_url = in.readString();
        this.n_voice_url = in.readString();
        this.n_isdone = in.readString();
    }

    public static final Parcelable.Creator<Notes> CREATOR = new Parcelable.Creator<Notes>() {
        @Override
        public Notes createFromParcel(Parcel source) {
            return new Notes(source);
        }

        @Override
        public Notes[] newArray(int size) {
            return new Notes[size];
        }
    };
}
