package com.example.apple.lingyongqian.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table e_personcards.
 */
public class PersonCards implements Parcelable {

    private Long p_id;
    private Long p_pid;
    private String p_add_date;
    private String p_sex;
    private String p_tell;
    private String p_describ;
    private String p_name;
    private String p_adress;
    private String p_email;

    public PersonCards() {
    }

    public PersonCards(Long p_id) {
        this.p_id = p_id;
    }

    public PersonCards(Long p_id, Long p_pid, String p_add_date, String p_sex, String p_tell, String p_describ, String p_name, String p_adress, String p_email) {
        this.p_id = p_id;
        this.p_pid = p_pid;
        this.p_add_date = p_add_date;
        this.p_sex = p_sex;
        this.p_tell = p_tell;
        this.p_describ = p_describ;
        this.p_name = p_name;
        this.p_adress = p_adress;
        this.p_email = p_email;
    }

    public Long getP_id() {
        return p_id;
    }

    public void setP_id(Long p_id) {
        this.p_id = p_id;
    }

    public Long getP_pid() {
        return p_pid;
    }

    public void setP_pid(Long p_pid) {
        this.p_pid = p_pid;
    }

    public String getP_add_date() {
        return p_add_date;
    }

    public void setP_add_date(String p_add_date) {
        this.p_add_date = p_add_date;
    }

    public String getP_sex() {
        return p_sex;
    }

    public void setP_sex(String p_sex) {
        this.p_sex = p_sex;
    }

    public String getP_tell() {
        return p_tell;
    }

    public void setP_tell(String p_tell) {
        this.p_tell = p_tell;
    }

    public String getP_describ() {
        return p_describ;
    }

    public void setP_describ(String p_describ) {
        this.p_describ = p_describ;
    }

    public String getP_name() {
        return p_name;
    }

    public void setP_name(String p_name) {
        this.p_name = p_name;
    }

    public String getP_adress() {
        return p_adress;
    }

    public void setP_adress(String p_adress) {
        this.p_adress = p_adress;
    }

    public String getP_email() {
        return p_email;
    }

    public void setP_email(String p_email) {
        this.p_email = p_email;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.p_id);
        dest.writeValue(this.p_pid);
        dest.writeString(this.p_add_date);
        dest.writeString(this.p_sex);
        dest.writeString(this.p_tell);
        dest.writeString(this.p_describ);
        dest.writeString(this.p_name);
        dest.writeString(this.p_adress);
        dest.writeString(this.p_email);
    }

    protected PersonCards(Parcel in) {
        this.p_id = (Long) in.readValue(Long.class.getClassLoader());
        this.p_pid = (Long) in.readValue(Long.class.getClassLoader());
        this.p_add_date = in.readString();
        this.p_sex = in.readString();
        this.p_tell = in.readString();
        this.p_describ = in.readString();
        this.p_name = in.readString();
        this.p_adress = in.readString();
        this.p_email = in.readString();
    }

    public static final Parcelable.Creator<PersonCards> CREATOR = new Parcelable.Creator<PersonCards>() {
        @Override
        public PersonCards createFromParcel(Parcel source) {
            return new PersonCards(source);
        }

        @Override
        public PersonCards[] newArray(int size) {
            return new PersonCards[size];
        }
    };
}
